version: '3.4'

services:
  api:
    build:
      context: .
    env_file: .env.docker
    restart: always
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    volumes:
      - /data
    logging:
      driver: none
